import { createElementSlider } from '../functions/functions';
import SubView from './subView';
const scaleUnits = {
  unitNames: ['min-value', '20-percent-value', '25-percent-value', '33-percent-value', '50-percent-value',
    '66-percent-value', '75-percent-value', '80-percent-value', 'max-value'],
  unitPositions: ['-0.5%', '20%', '25%', '33%', '50%', '66%', '75%', '80%', '100%'],
};
class ViewScale {
    private viewScale : HTMLElement;

    private units: Array<HTMLElement>;

    constructor(sliderBody:HTMLElement) {
      this.viewScale = createElementSlider(['progress__scale-bar']);
      sliderBody.appendChild(this.viewScale);
      this.units = [];
      this.init();
    }

    // updateViewScale(){const coords = this.getSliderParams();}
    init() {
      for (let i = 0; i < scaleUnits.unitNames.length; i += 1) {
        const barUnit = createElementSlider(['scale-bar__unit', `${scaleUnits.unitNames[i]}`]);
        barUnit.setAttribute('style', `left: ${scaleUnits.unitPositions[i]}`);
        this.units.push(barUnit);
        this.viewScale.appendChild(barUnit);
      }
      console.log(parseFloat(getComputedStyle(this.viewScale).width));
      // another units will be generated by methods
    }
}
export { ViewScale };
